---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  log_level: info

platforms:
  - name: centos-6.8
  - name: centos-7.2
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
  - name: ubuntu-16.04
    run_list:
      - recipe[apt]

verifier:
  name: inspec

suites:
  - name: default
    run_list:
      - recipe[simple_passenger::default]
      - recipe[lwrp_app::default]
    attributes:
      passenger:
        apps:
          attributes-app:
            git_repo: https://github.com/atheiman/simple-sinatra.git
            passengerfile:
              port: 8080
              environment: attributes-app-environment
            ruby_bin: /opt/chef/embedded/bin/ruby
